// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates customized website copy for tourism businesses using AI.
 *
 * - generateWebsiteCopy - A function that generates website copy.
 * - GenerateWebsiteCopyInput - The input type for the generateWebsiteCopy function.
 * - GenerateWebsiteCopyOutput - The return type for the generateWebsiteCopy function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateWebsiteCopyInputSchema = z.object({
  businessName: z.string().describe('The name of the tourism business.'),
  businessType: z
    .string()
    .describe(
      'The type of tourism business (e.g., hotel, travel agency, tour operator).'n    ),
  targetAudience: z
    .string()
    .describe('The target audience for the business (e.g., families, couples, adventurers).'),
  uniqueSellingPoints: z
    .string()
    .describe(
      'Unique selling points of the business, separated by commas (e.g., stunning views, excellent service, prime location).'n    ),
  websiteSection: z
    .string()
    .describe('The specific section of the website to generate copy for (e.g., About Us, Services, Contact).'),
  tone: z
    .string()
    .optional()
    .describe('The desired tone of the website copy (e.g., professional, friendly, adventurous).'),
});

export type GenerateWebsiteCopyInput = z.infer<typeof GenerateWebsiteCopyInputSchema>;

const GenerateWebsiteCopyOutputSchema = z.object({
  websiteCopy: z.string().describe('The generated website copy.'),
});

export type GenerateWebsiteCopyOutput = z.infer<typeof GenerateWebsiteCopyOutputSchema>;

export async function generateWebsiteCopy(
  input: GenerateWebsiteCopyInput
): Promise<GenerateWebsiteCopyOutput> {
  return generateWebsiteCopyFlow(input);
}

const generateWebsiteCopyPrompt = ai.definePrompt({
  name: 'generateWebsiteCopyPrompt',
  input: {schema: GenerateWebsiteCopyInputSchema},
  output: {schema: GenerateWebsiteCopyOutputSchema},
  prompt: `You are a marketing expert specializing in crafting compelling website copy for tourism businesses.

  Based on the following information, generate engaging and informative website copy for the specified section of the website.

  Business Name: {{{businessName}}}
  Business Type: {{{businessType}}}
  Target Audience: {{{targetAudience}}}
  Unique Selling Points: {{{uniqueSellingPoints}}}
  Website Section: {{{websiteSection}}}
  Tone: {{{tone}}}

  Website Copy:`,
});

const generateWebsiteCopyFlow = ai.defineFlow(
  {
    name: 'generateWebsiteCopyFlow',
    inputSchema: GenerateWebsiteCopyInputSchema,
    outputSchema: GenerateWebsiteCopyOutputSchema,
  },
  async input => {
    const {output} = await generateWebsiteCopyPrompt(input);
    return output!;
  }
);
