import type { Template, TemplateCategory, TemplateDesignStyle } from '@/lib/types';

export const mockTemplates: Template[] = [
  {
    id: 'template-1',
    name: 'Sunset Vista Hotel',
    category: 'Hotel',
    price: 199,
    designStyle: 'Luxury',
    imageUrl: 'https://placehold.co/600x400.png',
    previewUrl: 'https://placehold.co/1200x800.png',
    description: 'Elegant template for luxury hotels and resorts with breathtaking views.',
    longDescription: 'Sunset Vista offers a sophisticated design perfect for high-end hotels, resorts, and boutique accommodations. It features a stunning hero section, elegant gallery, and seamless booking integration placeholders. The warm color palette and spacious layout evoke a sense of luxury and relaxation.',
    features: ['Online Booking Placeholder', 'Gallery', 'Responsive Design', 'SEO Optimized'],
    dataAiHint: 'hotel luxury',
  },
  {
    id: 'template-2',
    name: 'Adventure Quest Tours',
    category: 'Tour Operator',
    price: 149,
    designStyle: 'Adventurous',
    imageUrl: 'https://placehold.co/600x400.png',
    previewUrl: 'https://placehold.co/1200x800.png',
    description: 'Dynamic template for tour operators offering exciting adventures.',
    longDescription: 'Adventure Quest is designed for tour operators and adventure travel companies. Its dynamic layout, bold typography, and action-oriented design elements inspire users to explore. Includes sections for tour listings, detailed itineraries, and an easy-to-use inquiry form.',
    features: ['Tour Listings', 'Itinerary Details', 'Inquiry Form', 'Video Background Support'],
    dataAiHint: 'adventure tour',
  },
  {
    id: 'template-3',
    name: 'Global Voyager Agency',
    category: 'Travel Agency',
    price: 179,
    designStyle: 'Modern',
    imageUrl: 'https://placehold.co/600x400.png',
    previewUrl: 'https://placehold.co/1200x800.png',
    description: 'Sleek and modern template for professional travel agencies.',
    longDescription: 'Global Voyager provides a clean, modern, and professional look for travel agencies. It emphasizes trust and efficiency with clear calls to action, destination showcases, and testimonial sections. The minimalist design ensures fast loading times and a great user experience across all devices.',
    features: ['Destination Showcase', 'Package Deals', 'Testimonials', 'Blog Section'],
    dataAiHint: 'travel agency',
  },
  {
    id: 'template-4',
    name: 'Culinary Canvas Restaurant',
    category: 'Restaurant',
    price: 99,
    designStyle: 'Minimalist',
    imageUrl: 'https://placehold.co/600x400.png',
    previewUrl: 'https://placehold.co/1200x800.png',
    description: 'A tasteful and minimalist template for restaurants and cafes.',
    longDescription: 'Culinary Canvas offers a clean and elegant design to showcase your restaurant, cafe, or bistro. It features beautiful menu displays, an online reservation placeholder, and a gallery to highlight your dishes and ambiance. The minimalist approach puts the focus on your culinary creations.',
    features: ['Menu Display', 'Reservation Form Placeholder', 'Photo Gallery', 'Contact & Map'],
    dataAiHint: 'restaurant food',
  },
  {
    id: 'template-5',
    name: 'Cityscape Attractions',
    category: 'Attraction',
    price: 129,
    designStyle: 'Classic',
    imageUrl: 'https://placehold.co/600x400.png',
    previewUrl: 'https://placehold.co/1200x800.png',
    description: 'Timeless design for showcasing local attractions and landmarks.',
    longDescription: 'Cityscape Attractions is a classic and informative template ideal for museums, historical sites, and local landmarks. It provides sections for visitor information, event calendars, ticket purchasing links, and rich historical content. The design is user-friendly and accessible.',
    features: ['Visitor Information', 'Event Calendar', 'Ticket Links', 'Interactive Map'],
    dataAiHint: 'city attraction',
  },
];

export const templateCategories: TemplateCategory[] = ['Hotel', 'Travel Agency', 'Tour Operator', 'Restaurant', 'Attraction'];
export const templateDesignStyles: TemplateDesignStyle[] = ['Modern', 'Luxury', 'Minimalist', 'Adventurous', 'Classic'];
